### ISSUE TITLE
[feature-request] Add TailwindCSS 

### ISSUE THREAD

**Issue by richjdsmith** [gabrielecanepa/middleman-webpack#1]
Would love to see the option to add TailwindCSS. Since this project seems built around going from nothing to something quick, there is nothing faster for CSS than tailwind 😆

Cheers for the great projcet btw!

**Comment by gabrielecanepa** [comment]
Hey @richjdsmith, thanks for the suggestion, but I'd rather keep the template with no preinstalled design systems since I'm currently using different libraries and components from project to project. 

I'm writing a small documentation where I'll explain how to get the most out of the template, including how to import custom libraries and organize your assets.

Thanks for the support! 🙌
